### ISSUE TITLE
Logo for this project

### ISSUE THREAD

**Issue by nunojesus** [MoePlayer/vue-aplayer#10]
Hello I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects, I would like to know if you are interested that I make a logo for this your project ?.

Greetings

Nuno Jesus

**Comment by u3u** [comment]
😘 Wow, welcome! thank you very much!

**Comment by nunojesus** [comment]
Great!  Do you have any special requests for logo design? how do you example colors? type of letters? do you have some idea for the logo? what kind of logos do you like?

Greetings!
Nuno Jesus

**Comment by u3u** [comment]
Sorry, I didn't reply in time. I just returned home.
Since this project is a component of [Vue.js](https://vuejs.org/), so I think the logo should be able to simultaneously highlight [Vue.js](https://vuejs.org/) and music player combined.
I don't really understand design, but I found some logos for your reference:

<img src="https://vuepress.vuejs.org/hero.png" width="100px">
<img src="https://file.iviewui.com/logo.svg" width="100px">
<img src="https://user-images.githubusercontent.com/20062482/40546028-88c1536c-6060-11e8-9f28-79d44a92fb4f.png" width="400px">

Similar to this, you are free to design! Thanks again!

**Comment by nunojesus** [comment]
Hello, I create this design, see if you like it or not.

![vue](https://user-images.githubusercontent.com/34600369/40580283-61d10e86-6133-11e8-92f9-3d105bc386a2.png)

**Comment by u3u** [comment]
Awesome! I like it so much! 😘
I will add you as a contributor in the README.md display, thank you very much! 🎉

**Comment by nunojesus** [comment]
Im Happy that you like it!
Im going to send you the png files of this files, can I make a pull request?

Greetings!

**Comment by u3u** [comment]
Of course! welcome!
