### ISSUE TITLE
music prop validation

### ISSUE THREAD

**Issue by ghost** [MoePlayer/vue-aplayer#128]
Getting this error. Even if i enter every info in music prop.
![screen shot 2018-08-27 at 15 43 34](https://user-images.githubusercontent.com/1254613/44660405-27478f80-aa10-11e8-8b4c-b14a86905f54.png)

This is example. mp3 path is correct.
<img width="292" alt="screen shot 2018-08-27 at 15 44 24" src="https://user-images.githubusercontent.com/1254613/44660406-29115300-aa10-11e8-9b81-ae0e58cf7212.png">

**Comment by u3u** [comment]
Sorry, it looks like you are using this [vue-aplayer](https://github.com/SevenOutman/vue-aplayer)? 
If not, then `src` should be changed to `url` and should use [`audio`](http://aplayer.netlify.com/docs/guide/options.html#audio) instead of `music` 😄

You should install this module with `yarn add @moefe/vue-aplayer`

Related issue: https://github.com/SevenOutman/vue-aplayer/issues/99

**Comment by ghost** [comment]
You are right. Thank you. And i have already opened issue there too.
